### ISSUE TITLE
Please dont panic on bind

### ISSUE THREAD

**Issue by numfin** [loyd/clickhouse.rs#103]
Could you please implement safe `.bind()` api via `Result<T, E>` or at  least option of `.bind_safe()`
Ofc idiomatic would be `bind()` and `bind_unsafe()`, but people always can use `.unwrap()` so i dont see any reason to panic at runtime

**Comment by loyd** [comment]
It depends on the source of the SQL query.

If it's written in place, the wrong binding is the programmer's error, so it panics now. It shouldn't be handled anyway (it's not an operational error) and should be fixed. This is the default behavior. 

However, if the query is gotten from somewhere (and somehow it's expected to contains `?` or `?fields`) it can be considered as an operational error. In this case I think some `try_bind() -> Result` can be provided.

**Comment by loyd** [comment]
On the other hand, `bind()` already results in errors in some cases instead of panicking, so I think I can make it more panic-free in the remaining cases.
