### ISSUE TITLE
Support Reqwest as an underlying client

### ISSUE THREAD

**Issue by blind-oracle** [loyd/clickhouse.rs#106]
Current `hyper-tls` dependency brings OpenSSL which sucks when cross-compiling e.g. to MUSL static.
Making it depend on `rustls` instead would be nice somehow.

Ideally maybe we can have some generic trait like the sealed `HttpClient` but public and with generic `Request`/`Response` from an `http` crate and `Body` from `http_body`. 

I can try to make a PR if that approach is acceptable.

**Comment by cole-h** [comment]
https://github.com/loyd/clickhouse.rs/pull/102 will at least make it possible to use `rustls` instead of openssl.

**Comment by blind-oracle** [comment]
@cole-h Yeah I did that in my fork already before I saw the others :) But I guess `reqwest` is more mainstream since `hyper` is kind of hiding its clients in `1.0` release...

**Comment by loyd** [comment]
I have a branch with hyper-v1 and rustls, but not enough tested yet. And because of #102 I need some time to figure out how I should merge these all together (or just close that PR, sorry)

**Comment by loyd** [comment]
hyper v1 is merged in the master branch. Now, either @cole-h or I should rebase https://github.com/loyd/clickhouse.rs/pull/102 to finally bring `rustls` and release a new version.

**Comment by loyd** [comment]
Note also, I'm not going to support the `reqwest` crate for now, because it's too high-level and can complicate future optimizations. Moreover, I want to have tcp+Native mode in the future.

I've renamed the issue because it's about supporting `rustls`, not the `reqwest` backend.
