### ISSUE TITLE
Update crates.io package

### ISSUE THREAD

**Issue by densumesh** [loyd/clickhouse.rs#111]
The crates.io package is currently not updated which bottlenecks us. It would be awesome to get a a new cargo version!

**Comment by loyd** [comment]
Hi, do you mean [Unreleased](https://github.com/loyd/clickhouse.rs/blob/master/CHANGELOG.md#unreleased---releasedate)?

So sorry about it, I was preparing `v0.12.0` and two moments are only in branches (supporting for `rustls` and migrating to hyper v1, which are breaking changes), so I was hoped to make all these breaking changes at once.

However, I was absorbed in my work and postponed releasing =(

I can release `v0.12.0` right now without rustls and hyper v1 if you're interested in some unreleased features.

**Comment by dgrr** [comment]
I think releasing now is ok, if you can attach issues here about rustls and hyper I can try to help

**Comment by dgrr** [comment]
@densumesh you can use `clickhouse = { git = "https://github.com/loyd/clickhouse.rs" }` to use the latest version. I think it would be more important to fix bugs.
@loyd do you have specific issues that can be solved, I could try to contribute

**Comment by loyd** [comment]
Now the support for hyper-v1 is merged into the master branch, so after rebasing #102 I'm going to release v0.12

**Comment by densumesh** [comment]
Thank you so much! We actually had a bug in 0.11 with the insertion not including the options passed in when creating the client, that got solved in a recent PR. This is for a CLI we are publishing so unfortunately you can't use git versions in the Cargo.toml.

**Comment by loyd** [comment]
v0.12.0 is finally released: https://github.com/loyd/clickhouse.rs/blob/master/CHANGELOG.md#0120---2024-07-16

Feel free to complain if something is wrong =)
