### ISSUE TITLE
When there's some error in query iterator just hangs forever without returning any errors

### ISSUE THREAD

**Issue by let4be** [loyd/clickhouse.rs#12]
Let's say I do 

```rust
let cursor = client.query("SELECT bla, wtf FROM ?").bind("some_table").fetch::<SomeType<'_>>();
let wtf = cursor.as_mut().unwrap().next().await;
```
hangs forever never to return...

same happens without binding table name if I just make a mistake in query syntax - errors swallowed, iterator hangs

**Comment by loyd** [comment]
Hm, it's easily to provide a helper to use as `bind(AsIdentifier("some_table"))`
