### ISSUE TITLE
Custom implementation of serialization for types

### ISSUE THREAD

**Issue by zezic** [loyd/clickhouse.rs#14]
I have the next struct:
```rust
use serde_derive::{Deserialize, Serialize};
use clickhouse::Reflection;

#[derive(Clone, Reflection, Deserialize, Serialize)]
pub enum LogLevel {
    DEBUG,
    INFO,
    WARNING,
    ERROR
}

#[derive(Clone, Reflection, Deserialize, Serialize)]
pub struct LogEntry {
    level: LogLevel,
    message: String,
}
```
When I'm trying to insert `LogEntry` struct into database I get the next panic:
```
thread 'tokio-runtime-worker' panicked at 'not yet implemented', /home/zezic/.cargo/registry/src/github.com-1ecc6299db9ec823/clickhouse-0.6.5/src/rowbinary/ser.rs:111:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
which points to another `todo!()` in the serialization source code:
```rust
    #[inline]
    fn serialize_unit_variant(
        self,
        _name: &'static str,
        _variant_index: u32,
        _variant: &'static str,
    ) -> Result<()> {
        todo!();
    }
```
What is the best way to satisfy types with the custom serialization implementation?

**Comment by loyd** [comment]
Thanks for the question!

To work with `Enum8`/`Enum16` it's useful to use the [serde_repr](https://docs.rs/serde_repr/0.1.7/serde_repr/) crate. I've added [an example](https://github.com/loyd/clickhouse.rs/blob/master/examples/enums.rs) to show how to use it.

Generally, arbitrary Rust enums cannot be represented in CH types and will always require special handling. However, some cases (like your one) can be handled automatically in the future, but with additional conversations and maybe requests for a table schema before INSERT statements.
