### ISSUE TITLE
Help: Float not working when fetch_all

### ISSUE THREAD

**Issue by selvavm** [loyd/clickhouse.rs#29]
When I do `fetch_all::<(u32, f64, u32)>()` it is throwing an error,

`the trait bound (u32, f64, u32): clickhouse::Row is not satisfied`. 

Could you help me here?

**Comment by loyd** [comment]
Hello. I've added `Primitive` instances for `f32` and `f64`. Released in v0.9.3

**Comment by selvavm** [comment]
Thanks a lot @loyd.
