### ISSUE TITLE
Update tokio ecosystem to 1.0

### ISSUE THREAD

**Issue by tekjar** [loyd/clickhouse.rs#3]
I think it's now safe to update to tokio 1.0, bytes 1.0 and hyper 0.14

**Comment by loyd** [comment]
Yep, I'll try to do it today/tomorrow.

Actually, I want to make the crate runtime-agnostic in order to support `async-std` and `glommio`, but it requires more work (get rid of hyper and so on).

**Comment by loyd** [comment]
`async-compression` uses `bytes v0.5` (even after https://github.com/Nemo157/async-compression/issues/110)

`clickhouse` uses `async-compression` to implement HTTP compression (gzip, zlib and brotli). Actually, it's not very useful because of lz4

**Comment by tekjar** [comment]
Ahh..If it's not very useful, is it possible to disable async-compression and update major release?

**Comment by loyd** [comment]
Yes, probably. I'll spend a little more time today. If I don't find a good solution, I'll throw out HTTP compression support.

**Comment by urumo** [comment]
Any updates on the status of this issue?

**Comment by loyd** [comment]
Sorry for long delay in reply. `clickhouse 0.6.0` uses tokio v1, hyper v0.14, bytes v1
