### ISSUE TITLE
Help: Float not working when fetch_all

### ISSUE THREAD

**Issue by selvavm** [loyd/clickhouse.rs#31]
Hi @loyd 

You have closed the issue but still it is not working. I am getting below error 
`the trait bound f64: clickhouse::row::Primitive is not satisfied`
`required because of the requirements on the impl of Row for f64`

Below is my code

    let r_ts = ts_client
          .query(&query)
          .fetch_all::<f64>()
          .await.unwrap();

Below is my dependencies,

    [dependencies]
    clickhouse = "0.9.3"
    tokio = { version = "1.15.0", features = ["full"] }

**Comment by selvavm** [comment]
Hi @loyd 

I find that if I use a Struct with `Row` implementation and the Struct has a field with `f32` it is working. Not sure why direct `f32` is not working.

Thanks,

**Comment by loyd** [comment]
It was a bug in the macro that implements `Primitive` for types. `f64` was the last one on that list. Fixed in https://github.com/loyd/clickhouse.rs/commit/30882a30863984d515ab8b24c518dae6eb21d0ce
