### ISSUE TITLE
Feature Request: Can you support (T,T) in Bind?

### ISSUE THREAD

**Issue by selvavm** [loyd/clickhouse.rs#33]
Thanks @loyd for your support. I don't see a implementation for (T,T) bind which Clickhouse supports. I saw the code but was not able to write my own code and send a PR (I am not there in Rust yet). Can you support me in this? I am willing to send a PR if you could suggest how I can solve it.

**Comment by loyd** [comment]
Makes sense.

Also, you can try to use an array instead, it's applicable in many cases too.

**Comment by loyd** [comment]
I've implemented `Bind` for all `Serialize` instances, so now it should work. Check `master`, I'm going to release a new version soon.
