### ISSUE TITLE
Version published on crates.io does not match what's on GitHub

### ISSUE THREAD

**Issue by scrabsha** [loyd/clickhouse.rs#35]
The title says everything. According to [the crates.io page](https://crates.io/crates/clickhouse), the latest version of `clickhouse` is `0.10.0`. As I'm writing this issue, the version of `clickhouse` from this repository's `Cargo.toml` is [`0.9.3`](https://github.com/loyd/clickhouse.rs/blob/f40a1d1f55091310d09015fe5063e4d28cbd66a7/Cargo.toml#L3).

Thank you for your work on this crate!

**Comment by loyd** [comment]
Uh, my mistake, sorry!
