### ISSUE TITLE
Date type 

### ISSUE THREAD

**Issue by makorne** [loyd/clickhouse.rs#4]
Please, add Date type because it is massively used even in Yandex itself.

> Кстати, структура точно такая же, как в Яндекс.Метрике для таблиц просмотров событий. Номер счетчика, т. е. идентификатор сайта, потом дата идет
 (c) Milovidov

Date is often needed for queres like: `... WHERE _date BETWEEN '2020-12-01' AND '2020-12-30'`

Thank you for great crate!

**Comment by loyd** [comment]
Sorry for the delay.

I think you can use `i64` (for `DateTime64`) or `i32` (for `DateTime32`), [example](https://github.com/Kraken-CI/kraken/blob/335badd85b5943ef24a7b77c236f2db21954fe55/clickhouse-proxy/src/main.rs#L27).

Meanwhile, I leave this issue open, maybe it's possible to support `SystemTime` and `chrono`.
