### ISSUE TITLE
Support for `Array(UUID)`?

### ISSUE THREAD

**Issue by gd87429** [loyd/clickhouse.rs#55]
Didn't see it in https://github.com/loyd/clickhouse.rs/blob/master/tests/test_uuid.rs

Is there a way to work with `Vec<uuid::Uuid>`?

**Comment by loyd** [comment]
I see only one way to do it, using a wrapper:
```rust
struct Uuid(#[serde(with = "clickhouse::serde::uuid")] uuid::Uuid)

struct Row {
    list: Vec<Uuid>
}
```

Although `clickhouse::serde::uuid::seq` can be provided, I haven't seen this approach before.

**Comment by gd87429** [comment]
I don't know about `::seq`, but a wrapper seems to do the trick. Thank you.
