### ISSUE TITLE
CANNOT_READ_ALL_DATA on inserter commit/end

### ISSUE THREAD

**Issue by jjtt** [loyd/clickhouse.rs#57]
I suspect that I'm doing something wrong, but I'm trying to use an inserter to write many rows to a ClickHouse db and started getting CANNOT_READ_ALL_DATA errors from the DB.

Created this simple program that demonstrates the problem while inserting just a single row: https://github.com/jjtt/clickhouse-cannot-read-all-data:
1. `run_clickhouse_server.sh` - to start the latest ClickHouse docker image
2. `cargo run`
3. panic:
   ```
   thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BadResponse("Code: 33. DB::Exception: Cannot read all data. Bytes read: 1. Bytes expected: 8.: (at row 1)\n: While executing BinaryRowInputFormat. (CANNOT_READ_ALL_DATA) (version 23.2.3.17 (official build))")', src/main.rs:23:26
   ```

**Comment by loyd** [comment]
Hi, you define `end_time` in SQL as non nullable, but in your Row type as `end_time: Option<i64>`.

Is this code generated by ch2rs? Or patched by yourself?

**Comment by loyd** [comment]
Ideally, it should be detected by the library, but it's harder for `INSERT` queries (because requires `SELECT`s to fetch a schema).

Related to https://github.com/loyd/clickhouse.rs/issues/10
