### ISSUE TITLE
Bug `Cannot read  all data`, after calling `end()`

### ISSUE THREAD

**Issue by kylinholmes** [loyd/clickhouse.rs#59]
## Panic info
```sh
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BadResponse("Code: 33. DB::Exception: Cannot read all data. Bytes read: 6. Bytes expected: 56.: (at row 2)\n: While executing BinaryRowInputFormat. (CANNOT_READ_ALL_DATA) (version 23.1.2.9 (official build))")', src/xxx.rs:181:40
```
error occur in `insert.end().await.unwrap()`
## Source code
```rust
  for (symbol_id, (total, cnt)) in records.iter() {
      let cli = make_client(url, db, table).await?;
      let mut insert = cli.inserter(table)?;
      ...
      insert.write(&r).await.unwrap();
      insert.commit().await.unwrap();
      insert.end().await.unwrap();
  };
```
here I tried `cli.insert()` `cli.inserter()`, 
also try to **drop table**, and **create a new one**,
but it doesn't help

**Comment by kylinholmes** [comment]
Sorry, I made a mistake, I use a duplicate value as primary key.
I realized it, after I print the record.

**Comment by loyd** [comment]
@kylinholmes, can you provide more info because using duplicate values as PK is valid for CH

**Comment by kylinholmes** [comment]
Ok, the structure is like:
```rust
#[derive(Debug, Row, Deserialize, Serialize)]
struct Stat {
    datetime: i64,
    xxx: String,
    yyy: i32,
}
```
and I use `datetime` as PK, following code to create a table:
```rust
cli.query(r"
CREATE TABLE IF NOT EXISTS ?.?(
    datetime DateTime64(0, 'Asia/Shanghai'),
    ....
)
ENGINE = MergeTree
ORDER BY datetime
PRIMARY KEY datetime
")
.bind(sql::Identifier(db))
.bind(sql::Identifier(table))
.execute().await?;
```

When I calling `end().await?`, the panic just happened.
after I checked data, I found that the value of `datetime` is duplicate as following, which I never thought it would be.
![image](https://user-images.githubusercontent.com/45586871/236479454-6cef0de2-0da1-4c28-86c5-015e9f1ff613.png)

After I changed ddl, everything is Ok:
```SQL
CREATE TABLE IF NOT EXISTS ?.?(
    datetime DateTime64(0, 'Asia/Shanghai'),
    xxx String,
    yyy Int32,
    ...
)
ENGINE = MergeTree
ORDER BY (datetime, xxx, yyy)
PRIMARY KEY (datetime, xxx, yyy)
```

**Comment by kylinholmes** [comment]
@loyd Do you have any thoughts on this bug？
