### ISSUE TITLE
Error messages are not decompressed

### ISSUE THREAD

**Issue by ods** [loyd/clickhouse.rs#6]
For all compressions except None the returned message is broken. E.g. for gzip it looks like:

```Error: BadResponse("\u{1f}�\u{8}\u{0}\u{0}\u{0}\u{0}\u{0}\u{4}\u{3}\u{2}�9?%�J��PG!U/%�� \'�2$��DCS�V����ʵ\"9��$3?�J�%�$1)�8U!\u{5}��O-�S/QH��,.Q�(K-*���S02�3�3�3U��OK�L�L�QH*��I���\u{2}\u{0}\u{0}\u{0}��\u{3}\u{0}\u{11}�\u{7f}\u{8}o\u{0}\u{0}\u{0}")```

**Comment by loyd** [comment]
Closed in #7
